bugtracker_project/bugs_app/urls.py
from django.urls import path
from bugs_app import views

urlpatterns = [
    path('<int:id>/',views.list_bugs,name='bug_list'),
    path('addbug/<int:project_id>/',views.bug_add,name='bugform'),
    path('delete/<int:project_id>/<int:bug_id>',views.bug_delete,name = 'bug_delete')
]

bugtracker_project/bugtracker_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('projects_app.urls')),
    path('bug/',include('bugs_app.urls')),
]

bugtracker_project/projects_app/urls.py
from django.urls import path
from projects_app import views

urlpatterns = [
    path('',views.home,name='home'),
    path('createproject/',views.add_project,name='addproject')
]

bugtracker_project/bugs_app/models.py
from django.db import models
from projects_app.models import Project

class Bug(models.Model):

    PRIORITY_CHOICES = [
        ('LO','Low'),
        ('MD','Medium'),
        ('HI','High')
    ]
    STATE_CHOICES = [
        ('RE','Resolved'),
        ('UN', 'Unresolved')
    ]

    project_id = models.ForeignKey(Project, on_delete=models.CASCADE, default='0')
    name = models.CharField(max_length=50)
    desc = models.TextField()
    priority = models.CharField(max_length=2, choices = PRIORITY_CHOICES)
    state = models.CharField(max_length=2, choices = STATE_CHOICES)

    def __str__(self):
        return self.name

bugtracker_project/projects_app/models.py
from django.db import models
from django import forms

class Project(models.Model):
    name = models.CharField(max_length=50)
    organization_name = models.CharField(max_length=70)
    technology = models.CharField(max_length=50)

    def __str__(self):
        return self.name

bugtracker_project/bugs_app/forms.py
from django import forms
from .models import Bug

class AddBugForm(forms.ModelForm):
    class Meta:
        model = Bug
        fields = ('name','desc','priority','state')
        widgets = {
            'name': forms.TextInput(attrs = {
                'class': 'form-control'
            }),
            'desc': forms.Textarea(attrs = {
                'class': 'form-control'
            }),
            'priority': forms.Select(attrs = {
                'class': 'form-control'
            }),
            'state': forms.Select(attrs = {
                'class': 'form-control'
            })
        }

bugtracker_project/projects_app/forms.py
from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs = {
                'class': 'form-control'
            }),
            'organization_name': forms.TextInput(attrs = {
                'class': 'form-control'
            }),
            'technology': forms.TextInput(attrs = {
                'class': 'form-control'
            })
        }

bugtracker_project/bugs_app/views.py
from django.shortcuts import render, redirect, reverse
from .models import Bug
from projects_app.models import Project
from .forms import AddBugForm

def list_bugs(request,id):
    query_bugs = Bug.objects.filter(project_id=id)
    project = Project.objects.filter(id = id)[0]

    context = {
        'bugs_list': query_bugs,
        'project': project
    }
    return render(request, 'bugs_app/bugs.html', context)

def bug_add(request,project_id):

    if request.method == "POST":
        form = AddBugForm(request.POST)
        if form.is_valid():
            project = Project.objects.filter(id=project_id)[0]

            bug = form.save(commit = False)
            bug.project_id = project
            bug.save()
            a = reverse('bug_list', args=[project_id])
            
            return redirect(a)
            
    else:
        form = AddBugForm()
        
    context = {
        'form': form
    }

    return render(request,'bugs_app/addbugs.html', context)

def bug_delete(request,project_id,bug_id):
    project = Project.objects.filter(id = project_id)[0]
    bug = Bug.objects.filter(project_id = project,id = bug_id)[0]
    bug.delete()
    return redirect(reverse('bug_list', args=[project_id]))

bugtracker_project/projects_app/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import ProjectForm
from .models import Project

def home(request):
    project_list = Project.objects.all()
    page = request.GET.get('page',1)

    paginator = Paginator(project_list,2)
    try:
        project_list = paginator.page(page)
    except PageNotAnInteger:
        project_list = paginator.page(1)
    except EmptyPage:
        project_list = paginator.page(paginator.num_pages)
    context = {
        'projects': project_list,
    }
    return render(request, 'projects_app/home.html', context)

def add_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = ProjectForm()    
    
    context = {
        'form': form
    }
    return render(request, 'projects_app/add_project.html',context)

bugtracker_project/bugs_app/templates/bugs_app/addbugs.html
{% extends 'projects_app/base.html' %}
{% block addbugform %}

    <div class="container">
        <h1 class="display-4">Add Bug</h1>
        <form class="mt-5" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="project_name">Bug Name</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                {{ form.desc }}
            </div>
            <div class="form-group">
                <label for="priority">Priority</label>
                {{ form.priority }}
            </div>
            <div class="form-group">
                <label for="state">State</label>
                {{ form.state }}
            </div>
            
            <button type="submit" class="btn btn-primary">Add Bug</button>
        </form>
    </div>

{% endblock  %}

bugtracker_project/bugs_app/templates/bugs_app/bugs.html
{% extends 'projects_app/base.html' %}
{% block bug %}
    <div class="container">
        <h1 class="display-4 project-title">Project: </h1>
        <h1 class="display-4 project-name">{{project.name}}</h1>
        <table class="table mt-5"> 
            <thead>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Priority</th>
                <th scope="col">State</th>
                <th scope="col"></th>
            </thead>
            <tbody>
                {% for bug in bugs_list %}

                    <tr class="bug-row">
                        <th scope="row"> {{forloop.counter}} </th>
                        <td>{{bug.name}}</td>
                        <td>{{bug.desc}}</td>
                        <td>{{bug.get_priority_display}}</td>
                        <td>{{bug.get_state_display}}</td>
                        <td>
                            <a href=" {% url 'bug_delete' project.id bug.id %} "title="Delete Item">
                                <span class="material-icons delete-icon">
                                    delete
                                </span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="flex-container">
            <button type="button" id="add-project" class="my-2 btn btn-outline-primary" onclick="openbugform({{project.id}})">add bug</button>
        </div>
    </div>
{% endblock %}

bugtracker_project/projects_app/templates/projects_app/add_project.html
{% extends 'projects_app/base.html' %}
{% block addprojectform %}
    <div class="container">
        <h1 class="display-4">Add Project</h1>
        <form class="mt-5" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="project_name">Name</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="organization_name">Organization Name</label>
                {{ form.organization_name }}
            </div>
            <div class="form-group">
                <label for="project_technology">Technology</label>
                {{ form.technology }}
            </div>
            
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
    
    
{% endblock%}

bugtracker_project/projects_app/templates/projects_app/base.html
{% load static %}  
<!DOCTYPE html>  
<html lang="en">  
    <head>  
        <meta charset="UTF-8">  
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Bug Tracker</title>  
        <!-- Bootstrap files -->
        <link rel="stylesheet" href="{% static 'bootstrap-4.3.1/css/bootstrap.min.css' %}" >  
        <script type="text/javascript" src="{% static 'bootstrap-4.3.1/js/bootstrap.min.js' %}"></script>  
        <!-- css files -->
        <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
        <link rel="stylesheet" href="{% static 'css/bugs_list.css' %}">
        <link rel="stylesheet" href="{% static 'css/projects.css' %}">
        <link rel="stylesheet" href="{% static 'css/table.css' %}">
        <!--js files-->
        <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
        <!--link for google icons-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--link for google fonts-->
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Condensed&family=Nunito+Sans:wght@300&family=Playfair+Display&family=Red+Rose&family=Rowdies:wght@700&display=swap" rel="stylesheet"> 
    </head>  
    <body>  
        <nav class="navbar mb-3">
            <a class="navbar-brand" href=" {% url 'home' %} ">Bug Tracker</a>
        </nav>

        {% block addprojectform %}
        {% endblock addprojectform %}

        {% block home %}
        {% endblock home %}
        
        {% block bug %}
        {% endblock bug %}     

        {% block addbugform %}
        {% endblock addbugform %}   
    </body>  
</html>  

bugtracker_project/projects_app/templates/projects_app/home.html
{% extends 'projects_app/base.html' %}
{% block home %}
    <div class="container mt-3">
        <h1 class="display-4 project-title">Projects</h1>
        <table class="table mt-5"> 
            <thead>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Organization/Company</th>
                <th scope="col">Technology Used</th>
            </thead>
            <tbody>
                {% for project in projects %}
                    <tr>
                        <th scope="row"> {{forloop.counter}} </th>
                        <td><a href="{% url 'bug_list' project.id %}">{{project.name}}</a></td>
                        <td>{{project.organization_name}}</td>
                        <td>{{project.technology}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="flex-container">
            <button type="button" id="add-project" class="mt-5 btn btn-outline-primary" onclick="openprojectform()">add project</button>
        </div>

        <nav class="mt-5 pagination" aria-label="Page navigation">
            {% if projects.has_other_pages %}
                <ul class="pagination">
                    {% if projects.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ projects.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">&laquo;</span>
                        </li>
                    {% endif %}
                    
                    {% for i in projects.paginator.page_range %}
                        {% if projects.number == i %}
                            <li class="page-item active">
                                <span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    
                    {% if projects.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ projects.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    {% else %}

                        <li class="page-item disabled">
                            <span class="page-link">&raquo;</span>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </nav>

    </div>
{% endblock home %}